image: alpine/3.20
packages:
  - nodejs
  - npm
secrets:
  - e2e843cf-6f7e-4b74-989f-819a97ca70b8
  - 29d1827e-ceed-47b7-b8a1-109d2ce13454
sources:
  - https://git.sr.ht/~mattmundell/build
  - git+ssh://git@git.sr.ht/~mattmundell/eslint-config
environment:
  PKG: eslint-config
tasks:
  - mirror: |
      cd $PKG && ../build/bin/mirror
  - publish: |
      cd $PKG && ../build/bin/publish
