image: alpine/3.20
packages:
  - nodejs
  - npm
secrets:
  - e2e843cf-6f7e-4b74-989f-819a97ca70b8
  - 1815ea96-0015-4f6c-9b85-82dd3b70b437
sources:
  - https://git.sr.ht/~mattmundell/build
  - git+ssh://git@git.sr.ht/~mattmundell/eslint-config
environment:
  PKG: eslint-config
tasks:
  - mirror: |
      cd $PKG && ../build/bin/mirror
  - publish: |
      cd $PKG && ../build/bin/publish
