image: alpine/3.20
packages:
  - nodejs
  - npm
secrets:
  - e3a02b8f-1f91-4a2c-9744-3bf7bb0257d6
sources:
  - https://git.sr.ht/~mattmundell/build
  - git+ssh://git@git.sr.ht/~mattmundell/eslint-config
environment:
  PKG: eslint-config
tasks:
  - mirror: |
      cd $PKG && ../build/bin/mirror
